export const PUSH_NAVLIST = 'PUSH_NAVLIST';

export const DELETE_NAV = 'DELETE_NAV';

export const DELETE_ALL_NAV = 'DELETE_ALL_NAV';

export const SET_CURRENTNAME = 'SET_CURRENTNAME';

export const SET_EDITBLOG = 'SET_EDITBLOG';

export const SET_DFAFTCOUNT = 'SET_DFAFTCOUNT';

export const SET_BBSCOUNT = 'SET_BBSCOUNT';

export const SET_ONLINEARTICLECOUNT = 'SET_ONLINEARTICLECOUNT';

export const SET_USERCOUNT = 'SET_USERCOUNT';

export const SET_WALKINGBLOGCOUNT = 'SET_WALKINGBLOGCOUNT';

export const SET_BACKPATH = 'SET_BACKPATH';

export const SET_TYPE = 'SET_TYPE';

export const SET_ISQUOTE = 'SET_ISQUOTE';